name: yugioh-card-entry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install apt dependencies
        run: sudo apt install libgtk-3-dev

      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy,rustfmt
          default: true
          override: true

      - name: Build
        run: cargo +nightly build --all --release

      - name: Test
        run: cargo +nightly test

      - name: Static analysis
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Check code formatting
        run: cargo fmt -- --check